[Minor] Adding types to Switch component
dxc-technology/halstack-angular pull request #594
Opened 2022-01-20 15:58 UTC by GomezIvann

2022-01-20 16:10 UTC, mawelCaballero approved these changes

2022-01-20 16:27 UTC, mawelCaballero commented
Adding whitespace between Space and Margin types.

2022-01-20 16:28 UTC, mawelCaballero requested changes

2022-01-20 16:28 UTC, mawelCaballero commented on projects/dxc-ngx-cdk/src/lib/dxc-switch/dxc-switch.component.ts
> +  @Output() onChange: EventEmitter<boolean>;
EventEmitter is not a function. EventEmitter is an object class which emits custom events synchronously or asynchronously, and register handlers for those events by subscribing to an instance.
Can you change "This function will be called" with "This event will emit in case of ... "
And can you change "The new state ..." with "checked property value". ?

2022-01-20 16:32 UTC, Jialecl commented on projects/dxc-ngx-cdk/src/lib/dxc-switch/dxc-switch.component.ts
> +  | "xxlarge";
Add a space between both types for clearness.

2022-01-21 09:50 UTC, GomezIvann commented on projects/dxc-ngx-cdk/src/lib/dxc-switch/dxc-switch.component.ts
> +  @Output() onChange: EventEmitter<boolean>;
Done!

2022-01-21 09:50 UTC, GomezIvann commented on projects/dxc-ngx-cdk/src/lib/dxc-switch/dxc-switch.component.ts
> +  | "xxlarge";
Done!

2022-01-21 10:30 UTC, mawelCaballero approved these changes

2022-01-24 07:47 UTC, merged