Added tag types
dxc-technology/halstack-angular pull request #712
Opened 2022-02-22 13:08 UTC by raquelarrojo

2022-02-23 11:09 UTC, marcialfps requested changes
- Change in table properties: `labelPosition: 'before' | 'after'`

2022-02-23 11:09 UTC, marcialfps commented on projects/dxc-ngx-cdk-site/src/app/components/examples/tag/properties/tag-table-properties/tag-table-properties.component.html
>      <td></td>
Please, change `This function will be called when the user clicks the tag.` to `This event will emit in case the user clicks the tag.`

2022-02-24 07:56 UTC, raquelarrojo commented
> * Change in table properties: `labelPosition: 'before' | 'after'`

Done!

2022-02-24 07:57 UTC, raquelarrojo commented on projects/dxc-ngx-cdk/src/lib/dxc-tag/dxc-tag.component.ts
> +type Size = "small" | "medium" | "large" | "fillParent" | "fitContent";
Done! Also changed in the box.

2022-02-24 07:57 UTC, raquelarrojo commented on projects/dxc-ngx-cdk-site/src/app/components/examples/tag/properties/tag-table-properties/tag-table-properties.component.html
>      <td></td>
Done! also changed in the props table. Thanks!

2022-02-24 08:36 UTC, marcialfps approved these changes

2022-02-24 08:39 UTC, merged